def dataListOptions():
    return {
        "Anime": 0,
        "Apps": 1,
        "Documentaries": 2,
        "Games": 3,
        "Movies": 4,
        "Music": 5,
        "Other": 6,
        "TV": 7,
        "XXX": 8,
    }


def subDataOptions():
    return {
        "Dual Audio Torrents": 1,
        "Dubbed Torrents": 2,
        "Raw Torrents": 3,
        "Subbed Torrents": 4,
        "Android Torrents": 5,
        "iOS Torrents": 6,
        "Linux Torrents": 7,
        "Mac Torrents": 8,
        "Other Torrents 1": 9,
        "PC Software Torrents": 10,
        "Documentary Torrents": 11,
        "3DS Torrents": 12,
        "Dreamcast Torrents": 13,
        "DS Torrents": 14,
        "GameCube Torrents": 15,
        "Other Torrents 2": 16,
        "PC Game Torrents": 17,
        "PS1 Torrents": 18,
        "PS2 Torrents": 19,
        "PS3 Torrents": 20,
        "PS4 Torrents": 21,
        "PSP Torrents": 22,
        "Switch Torrents": 23,
        "Wii Torrents": 24,
        "Xbox Torrents": 25,
        "Xbox360 Torrents": 26,
        "3D Torrents": 27,
        "Bollywood Torrents": 28,
        "Divx/Xvid Torrents": 29,
        "Dubs/Dual Audio Torrents": 30,
        "DVD Torrents": 31,
        "h.264/x264 Torrents": 32,
        "HD Torrents": 33,
        "HEVC/x265 Torrents": 34,
        "Mp4 Torrents": 35,
        "SVCD/VCD Torrents": 36,
        "UHD Torrents": 37,
        "Video Torrents": 38,
        "AAC Torrents": 39,
        "Album Torrents": 40,
        "Box Set Torrents": 41,
        "Concerts Torrents": 42,
        "Discography Torrents": 43,
        "DVD Torrents": 44,
        "Lossless Torrents": 45,
        "MP3 Torrents": 46,
        "Other Torrents 3": 47,
        "Radio Torrents": 48,
        "Single Torrents": 49,
        "Video Torrents": 50,
        "Audiobook Torrents": 51,
        "Comics Torrents": 52,
        "E-Books Torrents": 53,
        "Emulation Torrents": 54,
        "Images Torrents": 55,
        "Mobile Phone Torrents": 56,
        "Nulled Script Torrents": 57,
        "Other Torrents 4": 58,
        "Sounds Torrents": 59,
        "Tutorials Torrents": 60,
        "Cartoon Torrents": 61,
        "Divx/Xvid Torrents": 62,
        "DVD Torrents": 63,
        "HD Torrents": 64,
        "HEVC/x265 Torrents": 65,
        "SD Torrents": 66,
        "SVCD/VCD Torrents": 67,
        "Games Torrents": 68,
        "Hentai Torrents": 69,
        "Magazine Torrents": 70,
        "Picture Torrents": 71,
        "Video Torrents": 72,
    }
